// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARC33cnUCriQKBBz-SbwfwOtED6g9YqYU',
    appId: '1:968288726776:web:847d3360182745914dd50d',
    messagingSenderId: '968288726776',
    projectId: 'portfolio-4029d',
    authDomain: 'portfolio-4029d.firebaseapp.com',
    storageBucket: 'portfolio-4029d.appspot.com',
    measurementId: 'G-P1KF0GSXM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgwexs3EJMNm-Avo50YTwHVOuOBIBv8c4',
    appId: '1:968288726776:android:f53183c3a3aac5a34dd50d',
    messagingSenderId: '968288726776',
    projectId: 'portfolio-4029d',
    storageBucket: 'portfolio-4029d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQyl2oKmExh1Gu3_KmOTKv7sny_LjsxY4',
    appId: '1:968288726776:ios:c09b83748da8653a4dd50d',
    messagingSenderId: '968288726776',
    projectId: 'portfolio-4029d',
    storageBucket: 'portfolio-4029d.appspot.com',
    iosClientId: '968288726776-93er0320racdrclibdv86tev66pebk06.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQyl2oKmExh1Gu3_KmOTKv7sny_LjsxY4',
    appId: '1:968288726776:ios:5ec061f35b8736c14dd50d',
    messagingSenderId: '968288726776',
    projectId: 'portfolio-4029d',
    storageBucket: 'portfolio-4029d.appspot.com',
    iosClientId: '968288726776-nak9dt6d013ou9ki3gt78rnns8qiku56.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio.RunnerTests',
  );
}
